name: Manual2
on: 
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        options:
          - info
          - warn
          - error
jobs:
  runs:
    runs-on: ubuntu-latest 
    steps:
      - run: echo "${{ inputs.log-level }}"